#!/bin/bash

#In this step, I usually prefer to use different tools for functional annotation and then compare the results across methods. Alternatively, the results can be combined, although this is a more aggressive strategy and requires additional justification, such as validation against known reference gene or protein sequences.

#1) functional annotation using metabolic
module load metabolic/4.0

METABOLIC-C.pl -t 34 -in-gn /path/to/your/directory/good_250bins \
   -r /path/to/your/directory/raw_ref_read.txt\
    -o/path/to/your/directory/metabolic_result

#2)functional annotation using eggnog
module load eggnog-mapper/2.1.12 
module load prokka/1.14.6

for file in arc_*.fa; do
    base_name=${file%.fa} 
    prokka --outdir ./"$base_name"_prokka_annotation --prefix "$base_name" --metagenome --kingdom Archaea --cpus 34 $file --centre X --compliant
done

for file in bac_*.fa; do
    base_name=${file%.fa} 
    prokka --outdir ./"$base_name"_prokka_annotation --prefix "$base_name" --metagenome --kingdom Bacteria --cpus 34 $file --centre X --compliant
done

#from previous step we will have all faa files for each bin
#we then use these faa files for functional annotation via eggnog
for file in *.faa; do
    base_name=${file%.faa} #use .faa file from prokka
    if [[ -f "${base_name}_RAST_eggnog.emapper.annotations" ]]; then
    echo "🔹 Skipping ${base_name}, ${base_name}_eggnog.emapper.annotations already exists."
    continue
  fi
    python3 $EGGNOG_MAPPER/emapper.py -i "$base_name".faa -o "$base_name"_RAST_eggnog --cpu 34 -m diamond
done

#3)functional annotation using kemet
for file in /path/to/your/directory/*.eggnog.emapper.annotations; do
  base_name=$(basename "${file%.eggnog.emapper.annotations}")
  ./path/to/your/directory/KEMET/kemet.py "/path/to/your/directory/${base_name}.eggnog.emapper.annotations" -a eggnog --skip_hmm --skip_gsmm --no_genome --as_kegg
done

#4)functional annotation using kofamscan
for file in *_prokka.fasta; do
    base_name=${file%_prokka.fasta} #_prokka.fasta files are actually renamed from faa files from prokka, as faa files must end with .fasta when using kofamscan
    exec_annotation -f mapper \
    -o "$base_name"_koala.txt $file -p /path/to/your/directory/KoFamDB20241013/profiles/ \
    -k /path/to/your/directory/KoFamDB20241013/ko_list --cpu 34 --tmp-dir . -E 1e-5
done

for file in arc_*_koala.txt; do
    base_name=${file%_koala.txt}
    KEGG-decoder --input $file --output  "$base_name"_KEGGDecoder.list  --vizoption static
done


for file in bac_*_koala.txt; do
    base_name=${file%_koala.txt}
    KEGG-decoder --input $file --output  "$base_name"_KEGGDecoder.list  --vizoption static
done













